# Generated by Django 5.1.5 on 2025-01-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=30)),
                ('city', models.CharField(default='Ahmedabad', max_length=30)),
                ('state', models.CharField(default='Gujarat', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone_num', models.BigIntegerField()),
                ('role', models.CharField(max_length=30)),
                ('work_schedule', models.CharField(max_length=20)),
                ('assigned_task', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('discount', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_info', models.BigIntegerField()),
                ('shop_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(blank=True, default='', upload_to='product_images/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_details', models.CharField(max_length=200)),
                ('product_status', models.CharField(max_length=50)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='RentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_deposit', models.IntegerField()),
                ('rent_amount', models.FloatField()),
                ('return_status', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='RentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('rent_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rentorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customize_pro_id', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('order_type', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=30)),
                ('total_amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=30)),
                ('delivery_status', models.CharField(max_length=30)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=30)),
                ('payment_status', models.CharField(max_length=30)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.invoice')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorder')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorder'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone_num', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userlogin'),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userlogin'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userlogin'),
        ),
        migrations.CreateModel(
            name='CustomizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customize_img', models.CharField(max_length=200)),
                ('customize_details', models.CharField(max_length=300)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userlogin')),
            ],
        ),
    ]
