# Generated by Django 5.1.6 on 2025-02-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_loginmodel_registermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='state',
        ),
    ]
