# Generated by Django 5.1.6 on 2025-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_area_city_remove_area_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactus_name', models.CharField(max_length=80)),
                ('contactus_email', models.EmailField(max_length=254)),
                ('contactus_phone', models.BigIntegerField()),
                ('contactus_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='loginmodel',
        ),
        migrations.DeleteModel(
            name='registermodel',
        ),
    ]
