# Generated by Django 5.1.6 on 2025-02-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactusmodel_delete_loginmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='phone_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.area'),
        ),
    ]
