# Generated by Django 5.1.6 on 2025-03-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userlogin_address_alter_userlogin_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeproduct',
            name='customize_img',
            field=models.ImageField(upload_to='customized_products/'),
        ),
    ]
