# Generated by Django 5.1.6 on 2025-03-13 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customizeproduct_customize_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorder')),
                ('rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rentorder')),
            ],
        ),
    ]
