# Generated by Django 5.1.6 on 2025-03-24 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_employee_assigned_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_status',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('employee_id', models.ForeignKey(limit_choices_to={'role': 'Delivery Person'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorder')),
                ('rent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.rentorder')),
            ],
        ),
    ]
