# Generated by Django 5.1.6 on 2025-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_delivery_employee_id_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeproduct',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='customizeproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
