# Generated by Django 5.1.6 on 2025-03-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customizeproduct_budget_customizeproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeproduct',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='customizeproduct',
            name='status',
            field=models.BooleanField(),
        ),
    ]
