# Generated by Django 5.1.4 on 2025-03-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cart_timestamp_alter_cart_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('regular', 'Regular')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
