# Generated by Django 5.1.4 on 2025-03-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_razorpaypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeproduct',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
