# Generated by Django 5.1.4 on 2025-03-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_customizeproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_task',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.razorpaypayment'),
        ),
    ]
