# Generated by Django 5.1.4 on 2025-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_assign_task_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_task',
            name='rent_id',
        ),
        migrations.AddField(
            model_name='assign_task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready')], default='Pen', max_length=30),
        ),
    ]
