# Generated by Django 5.1.4 on 2025-03-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_assign_task_rent_id_assign_task_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentdetail',
            old_name='rent_order_id',
            new_name='rent_order',
        ),
        migrations.RemoveField(
            model_name='rentdetail',
            name='product_id',
        ),
        migrations.AddField(
            model_name='rentorder',
            name='delivery_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Delivery'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to='myapp.userlogin'),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assign_task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='return_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='myapp.userlogin'),
        ),
    ]
