# Generated by Django 5.1.4 on 2025-03-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_rent_order_id_rentdetail_rent_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='delivery_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Delivery'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to='myapp.employee'),
        ),
    ]
