# Generated by Django 5.2 on 2025-04-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_rentorder_delivery_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
