# Generated by Django 5.2 on 2025-04-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='c_id',
        ),
    ]
