# Generated by Django 5.2 on 2025-04-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_orderitems_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='rentdetail',
            name='rent_order',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='sales_order_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customize_pro_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.finalorders'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RentDetail',
        ),
        migrations.DeleteModel(
            name='SalesDetail',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
