# Generated by Django 5.2 on 2025-04-15 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_payment_invoice_id_remove_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeproduct',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
