# Generated by Django 5.2 on 2025-04-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_customizeproduct_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
